# Generated by Django 5.0.7 on 2024-07-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='stock',
            name='graph_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
